module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      items: [
        'latest/get-started/introduction',
        'latest/get-started/quick-start',
        'latest/get-started/installation',
        'latest/get-started/process-model',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'latest/development/accessibility',
        'latest/development/using-native-node-modules',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'latest/performance/performance',
        'latest/performance/message-ports',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: [
        'latest/security/context-isolation',
        'latest/security/security',
      ],
    },
    {
      type: 'category',
      label: 'Distribution',
      items: [
        'latest/distribution/code-signing',
        'latest/distribution/mac-app-store-submission-guide',
        'latest/distribution/windows-store-guide',
        'latest/distribution/snapcraft',
        'latest/distribution/application-distribution',
      ],
    },
    {
      type: 'category',
      label: 'Testing And Debugging',
      items: [
        'latest/testing-and-debugging/using-selenium-and-webdriver',
        'latest/testing-and-debugging/debugging-main-process',
        'latest/testing-and-debugging/debugging-vscode',
        'latest/testing-and-debugging/devtools-extension',
        'latest/testing-and-debugging/application-debugging',
        'latest/testing-and-debugging/automated-testing-with-a-custom-driver',
        'latest/testing-and-debugging/testing-on-headless-ci',
        'latest/testing-and-debugging/testing-widevine-cdm',
      ],
    },
    {
      type: 'category',
      label: 'How To',
      items: [
        'latest/how-to/examples',
        'latest/how-to/dark-mode',
        'latest/how-to/desktop-environment-integration',
        'latest/how-to/fuses',
        'latest/how-to/in-app-purchases',
        'latest/how-to/keyboard-shortcuts',
        'latest/how-to/linux-desktop-actions',
        'latest/how-to/macos-dock',
        'latest/how-to/multithreading',
        'latest/how-to/native-file-drag-drop',
        'latest/how-to/notifications',
        'latest/how-to/offscreen-rendering',
        'latest/how-to/online-offline-events',
        'latest/how-to/progress-bar',
        'latest/how-to/recent-documents',
        'latest/how-to/repl',
        'latest/how-to/represented-file',
        'latest/how-to/spellchecker',
        'latest/how-to/updates',
        'latest/how-to/using-pepper-flash-plugin',
        'latest/how-to/web-embeds',
        'latest/how-to/windows-arm',
        'latest/how-to/windows-taskbar',
        'latest/how-to/sandbox',
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      items: [
        'latest/internals/electron-vs-nwjs',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'latest/resources/boilerplates-and-clis',
        'latest/resources/breaking-changes',
        'latest/resources/electron-timelines',
        'latest/resources/electron-versioning',
        'latest/resources/faq',
        'latest/resources/glossary',
        'latest/resources/support',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'latest/contributing/README',
        'latest/contributing/azure-vm-setup',
        'latest/contributing/build-instructions-gn',
        'latest/contributing/build-instructions-linux',
        'latest/contributing/build-instructions-macos',
        'latest/contributing/build-instructions-windows',
        'latest/contributing/build-system-overview',
        'latest/contributing/chromium-development',
        'latest/contributing/clang-format',
        'latest/contributing/clang-tidy',
        'latest/contributing/coding-style',
        'latest/contributing/debug-instructions-windows',
        'latest/contributing/debugging-instructions-macos',
        'latest/contributing/debugging-instructions-macos-xcode',
        'latest/contributing/goma',
        'latest/contributing/issues',
        'latest/contributing/patches',
        'latest/contributing/pull-requests',
        'latest/contributing/setting-up-symbol-server',
        'latest/contributing/source-code-directory-structure',
        'latest/contributing/testing',
        'latest/contributing/v8-development',
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Main Process Modules',
      items: [
        'latest/api/app',
        'latest/api/auto-updater',
        'latest/api/browser-view',
        'latest/api/browser-window',
        'latest/api/clipboard',
        'latest/api/content-tracing',
        'latest/api/crash-reporter',
        'latest/api/desktop-capturer',
        'latest/api/dialog',
        'latest/api/global-shortcut',
        'latest/api/in-app-purchase',
        'latest/api/ipc-main',
        'latest/api/menu',
        'latest/api/message-channel-main',
        'latest/api/message-port-main',
        'latest/api/native-image',
        'latest/api/native-theme',
        'latest/api/net',
        'latest/api/net-log',
        'latest/api/notification',
        'latest/api/power-monitor',
        'latest/api/power-save-blocker',
        'latest/api/process',
        'latest/api/protocol',
        'latest/api/screen',
        'latest/api/session',
        'latest/api/share-menu',
        'latest/api/shell',
        'latest/api/system-preferences',
        'latest/api/touch-bar',
        'latest/api/tray',
        'latest/api/web-contents',
        'latest/api/web-frame-main',
      ],
    },
    {
      type: 'category',
      label: 'Renderer Process Modules',
      items: [
        'latest/api/clipboard',
        'latest/api/context-bridge',
        'latest/api/crash-reporter',
        'latest/api/desktop-capturer',
        'latest/api/ipc-renderer',
        'latest/api/native-image',
        'latest/api/web-frame',
      ],
    },
    {
      type: 'category',
      label: 'Custom DOM Elements',
      items: [
        'latest/api/browser-window-proxy',
        'latest/api/file-object',
        'latest/api/webview-tag',
        'latest/api/window-open',
      ],
    },
    {
      type: 'category',
      label: 'Chromium and Node.js',
      items: [
        'latest/api/command-line-switches',
        'latest/api/environment-variables',
        'latest/api/extensions',
      ],
    },
    {
      type: 'category',
      label: 'Classes',
      items: [
        'latest/api/client-request',
        'latest/api/command-line',
        'latest/api/cookies',
        'latest/api/debugger',
        'latest/api/dock',
        'latest/api/download-item',
        'latest/api/incoming-message',
        'latest/api/menu-item',
        'latest/api/service-workers',
        'latest/api/touch-bar-button',
        'latest/api/touch-bar-color-picker',
        'latest/api/touch-bar-group',
        'latest/api/touch-bar-label',
        'latest/api/touch-bar-other-items-proxy',
        'latest/api/touch-bar-popover',
        'latest/api/touch-bar-scrubber',
        'latest/api/touch-bar-segmented-control',
        'latest/api/touch-bar-slider',
        'latest/api/touch-bar-spacer',
        'latest/api/web-request',
      ],
    },
    {
      type: 'category',
      label: 'API Structures',
      items: [
        'latest/api/structures/bluetooth-device',
        'latest/api/structures/certificate',
        'latest/api/structures/certificate-principal',
        'latest/api/structures/cookie',
        'latest/api/structures/cpu-usage',
        'latest/api/structures/crash-report',
        'latest/api/structures/custom-scheme',
        'latest/api/structures/desktop-capturer-source',
        'latest/api/structures/display',
        'latest/api/structures/event',
        'latest/api/structures/extension',
        'latest/api/structures/extension-info',
        'latest/api/structures/file-filter',
        'latest/api/structures/file-path-with-headers',
        'latest/api/structures/gpu-feature-status',
        'latest/api/structures/input-event',
        'latest/api/structures/io-counters',
        'latest/api/structures/ipc-main-event',
        'latest/api/structures/ipc-main-invoke-event',
        'latest/api/structures/ipc-renderer-event',
        'latest/api/structures/jump-list-category',
        'latest/api/structures/jump-list-item',
        'latest/api/structures/keyboard-event',
        'latest/api/structures/keyboard-input-event',
        'latest/api/structures/memory-info',
        'latest/api/structures/memory-usage-details',
        'latest/api/structures/mime-typed-buffer',
        'latest/api/structures/mouse-input-event',
        'latest/api/structures/mouse-wheel-input-event',
        'latest/api/structures/new-window-web-contents-event',
        'latest/api/structures/notification-action',
        'latest/api/structures/notification-response',
        'latest/api/structures/point',
        'latest/api/structures/post-body',
        'latest/api/structures/printer-info',
        'latest/api/structures/process-memory-info',
        'latest/api/structures/process-metric',
        'latest/api/structures/product',
        'latest/api/structures/protocol-request',
        'latest/api/structures/protocol-response',
        'latest/api/structures/protocol-response-upload-data',
        'latest/api/structures/rectangle',
        'latest/api/structures/referrer',
        'latest/api/structures/scrubber-item',
        'latest/api/structures/segmented-control-segment',
        'latest/api/structures/serial-port',
        'latest/api/structures/service-worker-info',
        'latest/api/structures/shared-worker-info',
        'latest/api/structures/sharing-item',
        'latest/api/structures/shortcut-details',
        'latest/api/structures/size',
        'latest/api/structures/task',
        'latest/api/structures/thumbar-button',
        'latest/api/structures/trace-categories-and-options',
        'latest/api/structures/trace-config',
        'latest/api/structures/transaction',
        'latest/api/structures/upload-data',
        'latest/api/structures/upload-file',
        'latest/api/structures/upload-raw-data',
        'latest/api/structures/web-source',
      ],
    },
  ],
};
