module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Get Started',
      items: [
        'latest/tutorial/introduction',
        'latest/why-electron',
        {
          type: 'category',
          label: 'Tutorial',
          items: [
            'latest/tutorial/tutorial-1-prerequisites',
            'latest/tutorial/tutorial-2-first-app',
            'latest/tutorial/tutorial-3-preload',
            'latest/tutorial/tutorial-4-adding-features',
            'latest/tutorial/tutorial-5-packaging',
            'latest/tutorial/tutorial-6-publishing-updating',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Processes in Electron',
      items: [
        'latest/tutorial/process-model',
        'latest/tutorial/context-isolation',
        'latest/tutorial/ipc',
        'latest/tutorial/sandbox',
        'latest/tutorial/message-ports',
      ],
    },
    {
      type: 'category',
      label: 'Best Practices',
      items: ['latest/tutorial/performance', 'latest/tutorial/security'],
    },
    {
      type: 'category',
      label: 'Examples',
      link: { type: 'doc', id: 'latest/tutorial/examples' },
      items: [
        'latest/tutorial/dark-mode',
        'latest/tutorial/devices',
        {
          type: 'doc',
          id: 'latest/tutorial/in-app-purchases',
          customProps: { platforms: ['mac'] },
        },
        'latest/tutorial/keyboard-shortcuts',
        'latest/tutorial/launch-app-from-url-in-another-app',
        {
          type: 'doc',
          id: 'latest/tutorial/linux-desktop-actions',
          customProps: { platforms: ['linux'] },
        },
        {
          type: 'category',
          label: 'Menus',
          link: { type: 'doc', id: 'latest/tutorial/menus' },
          items: [
            'latest/tutorial/application-menu',
            'latest/tutorial/context-menu',
            {
              type: 'doc',
              id: 'latest/tutorial/macos-dock',
              customProps: { platforms: ['mac'] },
            },
            'latest/tutorial/tray',
            'latest/tutorial/keyboard-shortcuts',
          ],
        },
        'latest/tutorial/multithreading',
        'latest/tutorial/native-file-drag-drop',
        'latest/tutorial/navigation-history',
        'latest/tutorial/notifications',
        'latest/tutorial/offscreen-rendering',
        'latest/tutorial/online-offline-events',
        'latest/tutorial/progress-bar',
        {
          type: 'doc',
          id: 'latest/tutorial/recent-documents',
          customProps: { platforms: ['mac', 'windows'] },
        },
        {
          type: 'doc',
          id: 'latest/tutorial/represented-file',
          customProps: { platforms: ['mac'] },
        },
        'latest/tutorial/spellchecker',
        'latest/tutorial/web-embeds',
        {
          type: 'doc',
          id: 'latest/tutorial/windows-taskbar',
          customProps: { platforms: ['windows'] },
        },
        {
          type: 'category',
          label: 'Window Customization',
          link: { type: 'doc', id: 'latest/tutorial/window-customization' },
          items: [
            'latest/tutorial/custom-title-bar',
            'latest/tutorial/custom-window-interactions',
            'latest/tutorial/custom-window-styles',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'latest/tutorial/accessibility',
        'latest/tutorial/installation',
        'latest/tutorial/asar-archives',
        'latest/tutorial/asar-integrity',
        'latest/tutorial/esm',
        'latest/tutorial/fuses',
        'latest/tutorial/window-state-persistence',
        'latest/tutorial/windows-arm',
      ],
    },
    {
      type: 'category',
      label: 'Native Node Modules',
      items: [
        'latest/tutorial/using-native-node-modules',
        {
          type: 'category',
          label: 'Tutorial: Native Code and Electron',
          items: [
            'latest/tutorial/native-code-and-electron',
            'latest/tutorial/native-code-and-electron-cpp-win32',
            'latest/tutorial/native-code-and-electron-swift-macos',
            'latest/tutorial/native-code-and-electron-cpp-linux',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Distribution',
      items: [
        'latest/tutorial/forge-overview',
        {
          type: 'category',
          label: 'Advanced Reference',
          link: { type: 'doc', id: 'latest/tutorial/distribution-overview' },
          items: [
            'latest/tutorial/application-distribution',
            'latest/tutorial/code-signing',
            'latest/tutorial/updates',
            {
              type: 'category',
              label: 'App Store Guides',
              items: [
                'latest/tutorial/mac-app-store-submission-guide',
                'latest/tutorial/windows-store-guide',
                'latest/tutorial/snapcraft',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing And Debugging',
      items: [
        'latest/tutorial/automated-testing',
        'latest/tutorial/debugging-main-process',
        'latest/tutorial/debugging-vscode',
        'latest/tutorial/repl',
        'latest/tutorial/devtools-extension',
        'latest/tutorial/application-debugging',
        'latest/tutorial/testing-on-headless-ci',
      ],
    },
    {
      type: 'category',
      label: 'References',
      items: [
        'latest/breaking-changes',
        'latest/tutorial/electron-timelines',
        'latest/tutorial/electron-versioning',
        'latest/faq',
        'latest/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'category',
          label: 'Build Instructions',
          link: { type: 'doc', id: 'latest/development/build-instructions-gn' },
          items: [
            'latest/development/build-instructions-linux',
            'latest/development/build-instructions-macos',
            'latest/development/build-instructions-windows',
            'latest/development/reclient',
          ],
        },
        {
          type: 'category',
          label: 'Debugging',
          link: { type: 'doc', id: 'latest/development/debugging' },
          items: [
            'latest/development/debugging-on-macos',
            'latest/development/debugging-on-windows',
            'latest/development/debugging-with-xcode',
            'latest/development/debugging-with-symbol-server',
          ],
        },
        {
          type: 'category',
          label: 'Development Guides',
          items: [
            'latest/development/api-history-migration-guide',
            'latest/development/clang-tidy',
            'latest/development/coding-style',
            'latest/development/creating-api',
            'latest/development/patches',
            'latest/development/source-code-directory-structure',
            'latest/development/style-guide',
            'latest/development/testing',
          ],
        },
        {
          type: 'category',
          label: 'GitHub',
          items: [
            'latest/development/issues',
            'latest/development/pull-requests',
          ],
        },
        {
          type: 'category',
          label: 'Upstream Development',
          items: [
            'latest/development/chromium-development',
            'latest/development/v8-development',
          ],
        },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'Main Process Modules',
      items: [
        'latest/api/app',
        'latest/api/auto-updater',
        'latest/api/base-window',
        {
          type: 'doc',
          id: 'latest/api/browser-view',
          customProps: { deprecated: true },
        },
        'latest/api/browser-window',
        'latest/api/clipboard',
        'latest/api/content-tracing',
        'latest/api/crash-reporter',
        'latest/api/desktop-capturer',
        'latest/api/dialog',
        'latest/api/global-shortcut',
        'latest/api/image-view',
        'latest/api/in-app-purchase',
        'latest/api/ipc-main',
        'latest/api/menu',
        'latest/api/menu-item',
        'latest/api/message-channel-main',
        'latest/api/message-port-main',
        'latest/api/native-image',
        'latest/api/native-theme',
        'latest/api/net',
        'latest/api/net-log',
        'latest/api/notification',
        'latest/api/power-monitor',
        'latest/api/power-save-blocker',
        'latest/api/process',
        'latest/api/protocol',
        'latest/api/push-notifications',
        'latest/api/safe-storage',
        'latest/api/screen',
        'latest/api/session',
        'latest/api/shared-texture',
        'latest/api/share-menu',
        'latest/api/shell',
        'latest/api/system-preferences',
        'latest/api/touch-bar',
        'latest/api/tray',
        'latest/api/utility-process',
        'latest/api/web-contents',
        'latest/api/web-contents-view',
        'latest/api/web-frame-main',
        'latest/api/view',
      ],
    },
    {
      type: 'category',
      label: 'Renderer Process Modules',
      items: [
        'latest/api/clipboard',
        'latest/api/context-bridge',
        'latest/api/crash-reporter',
        'latest/api/ipc-renderer',
        'latest/api/native-image',
        'latest/api/web-frame',
        'latest/api/web-utils',
      ],
    },
    {
      type: 'category',
      label: 'Utility Process Modules',
      items: [
        'latest/api/net',
        'latest/api/parent-port',
        'latest/api/system-preferences',
      ],
    },
    {
      type: 'category',
      label: 'Custom Web Features',
      items: [
        'latest/api/corner-smoothing-css',
        'latest/api/webview-tag',
        'latest/api/window-open',
      ],
    },
    {
      type: 'category',
      label: 'Chromium and Node.js',
      items: [
        'latest/api/command-line-switches',
        'latest/api/environment-variables',
        'latest/api/extensions',
      ],
    },
    {
      type: 'category',
      label: 'Classes',
      items: [
        'latest/api/client-request',
        'latest/api/clipboard-item',
        'latest/api/command-line',
        'latest/api/cookies',
        'latest/api/debugger',
        'latest/api/dock',
        'latest/api/download-item',
        'latest/api/extensions-api',
        'latest/api/incoming-message',
        'latest/api/ipc-main-service-worker',
        'latest/api/navigation-history',
        'latest/api/service-worker-main',
        'latest/api/service-workers',
        'latest/api/touch-bar-button',
        'latest/api/touch-bar-color-picker',
        'latest/api/touch-bar-group',
        'latest/api/touch-bar-label',
        'latest/api/touch-bar-other-items-proxy',
        'latest/api/touch-bar-popover',
        'latest/api/touch-bar-scrubber',
        'latest/api/touch-bar-segmented-control',
        'latest/api/touch-bar-slider',
        'latest/api/touch-bar-spacer',
        'latest/api/web-request',
        'latest/api/web-socket',
      ],
    },
    {
      type: 'category',
      label: 'API Structures',
      items: [{ type: 'autogenerated', dirName: 'latest/api/structures' }],
    },
  ],
};
