/**
 * Checks that `sidebars.js` and the API docs under `docs/latest/api`
 * agree with each other:
 *
 * - every API doc on disk has a sidebar entry (directly, or through an
 *   `autogenerated` item covering its directory), and
 * - every doc id referenced from any sidebar exists on disk.
 *
 * The docs are synced from `electron/electron` while the sidebar is
 * maintained by hand, so without this check new API pages silently
 * ship with no sidebar entry.
 */
import fs from 'node:fs/promises';
import path from 'node:path';

import { logger } from '@docusaurus/logger';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import sidebarsModule from '../sidebars.js';

const sidebars = sidebarsModule as SidebarsConfig;

const DOCS_ROOT = path.join(import.meta.dirname, '..', 'docs');
const API_DIR = 'latest/api';

/**
 * Doc ids under `API_DIR` that intentionally have no sidebar entry.
 */
const IGNORED_API_DOCS = new Set<string>([]);

const collectSidebarRefs = (
  sidebar: SidebarsConfig[string],
  docIds: Set<string>,
  autogeneratedDirs: Set<string>,
) => {
  if (!Array.isArray(sidebar)) {
    // Category shorthand: `{ 'Category label': [...items] }`
    for (const items of Object.values(sidebar)) {
      collectSidebarRefs(items, docIds, autogeneratedDirs);
    }
    return;
  }
  for (const item of sidebar) {
    if (typeof item === 'string') {
      docIds.add(item);
    } else if (item.type === 'doc' || item.type === 'ref') {
      docIds.add(item.id);
    } else if (item.type === 'autogenerated') {
      autogeneratedDirs.add(item.dirName);
    } else if (item.type === 'category') {
      if (item.link?.type === 'doc') {
        docIds.add(item.link.id);
      }
      collectSidebarRefs(item.items, docIds, autogeneratedDirs);
    }
  }
};

const collectDocIds = async (dir: string) => {
  const ids = new Set<string>();
  for await (const file of fs.glob(path.posix.join(dir, '**/*.{md,mdx}'), {
    cwd: DOCS_ROOT,
  })) {
    ids.add(file.replace(/\\/g, '/').replace(/\.mdx?$/, ''));
  }
  return ids;
};

const main = async () => {
  const sidebarDocIds = new Set<string>();
  const autogeneratedDirs = new Set<string>();
  for (const sidebar of Object.values(sidebars)) {
    collectSidebarRefs(sidebar, sidebarDocIds, autogeneratedDirs);
  }

  const isCovered = (id: string) =>
    sidebarDocIds.has(id) ||
    [...autogeneratedDirs].some((dir) => id.startsWith(`${dir}/`));

  const apiDocIds = await collectDocIds(API_DIR);
  const missingFromSidebar = [...apiDocIds]
    .filter((id) => !IGNORED_API_DOCS.has(id) && !isCovered(id))
    .sort();

  const allDocIds = await collectDocIds('.');
  const missingFromDisk = [...sidebarDocIds]
    .filter((id) => !allDocIds.has(id))
    .sort();

  let failed = false;

  if (missingFromSidebar.length > 0) {
    failed = true;
    logger.error(
      `${missingFromSidebar.length} API doc(s) under ${logger.path(
        `docs/${API_DIR}`,
      )} have no entry in ${logger.path('sidebars.js')}:`,
    );
    for (const id of missingFromSidebar) {
      logger.error(`  - ${id}`);
    }
    logger.info(
      `Add each one to the matching category in ${logger.path(
        'sidebars.js',
      )}, or to IGNORED_API_DOCS in ${logger.path(
        'scripts/check-sidebars.ts',
      )} if it should stay hidden.`,
    );
  }

  if (missingFromDisk.length > 0) {
    failed = true;
    logger.error(
      `${missingFromDisk.length} sidebar entr${
        missingFromDisk.length === 1 ? 'y' : 'ies'
      } in ${logger.path('sidebars.js')} point(s) to a doc that does not exist:`,
    );
    for (const id of missingFromDisk) {
      logger.error(`  - ${id}`);
    }
  }

  if (failed) {
    process.exit(1);
  }

  logger.success(
    `All ${apiDocIds.size} API docs are in the sidebar and all sidebar entries exist.`,
  );
};

main();
